version: '3.8'

services:
  app:
    build: .
    container_name: plutos-exchange
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - SESSION=${SESSION}
      - TARGET_USER=${TARGET_USER}
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
    volumes:
      - ./public:/app/public
      - ./views:/app/views
      - ./.env:/app/.env:ro
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
